dependencies {
    // Registrate
    api(libs.registrate)

    // Anvil Lib
    runtimeOnly(libs.anvillib)
    compileOnly(libs.anvillibConfig)
    compileOnly(libs.anvillibRecipe)
    interfaceInjectionData(libs.anvillibRecipe)
    compileOnly(libs.anvillibMoveableEntityBlock)
    interfaceInjectionData(libs.anvillibMoveableEntityBlock)
    compileOnly(libs.anvillibIntegration)

    // AnvilCraft
    implementation(libs.anvilcraft) { transitive = false }
    interfaceInjectionData(libs.anvilcraft) { transitive = false }

    // AnvilCraft: GuideME
    implementation(libs.anvilcraftguideme) { transitive = false }
    compileOnly("org.appliedenergistics:guideme:${libs.versions.guideme.get()}:api")
    runtimeOnly(libs.guideme)

    // JEI
    compileOnlyApi(libs.jeiCommonApi) { transitive = false }
    compileOnlyApi(libs.jeiForgeApi) { transitive = false }
    implementation(libs.jeiForgeImpl) { transitive = false }

    // Jade
    implementation(libs.jade)
}