# Jvm info
java_version=21
org.gradle.jvmargs=-Xmx2G -Dfile.encoding=UTF-8 -Dsun.jnu.encoding=UTF-8
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
## Environment info
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.152
neo_version_range=[21,)
loader_version_range=[4,)
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
## Upload info
upload=false
modrinth_id=xxxxx
curseforge_id=xxxxx
## Mod info
mod_id=anvilcraft_reverberation
mod_name=AnvilCraftReverberation
mod_license=LGPL-3.0 license
mod_version=0.1.0
maven_group=dev.anvilcraft.reverberation
mod_authors=Anvil-Dev
mod_description=AnvilCraftReverberation made by TB_pig
## Encoding info
systemProp.file.encoding=UTF-8
systemProp.sun.jnu.encoding=UTF-8
