[versions]
minecraft = "1.21.1"
neoForge = "21.1.217"
registrate = "MC1.21-1.3.0+62"
anvillib = "1.4.0+build.172"
anvilcraft = "1.5.1"
anvilcraft_guideme = "1.5.1-1+build.19"
modDevGradle = "2.0.78"
lombok = "8.7.1"
jei = "19.21.0.247"
jade = "15.3.4+neoforge"
guideme = "21.1.9"

[libraries]
registrate = { group = "com.tterrag.registrate", name = "Registrate", version.ref = "registrate" }
anvillib = { group = "dev.anvilcraft.lib", name = "anvillib-neoforge-1.21.1", version.ref = "anvillib" }
anvilcraft = { group = "dev.dubhe", name = "anvilcraft-neoforge-1.21.1", version.ref = "anvilcraft" }
anvilcraftguideme = { group = "dev.anvilcraft.guideme", name = "anvilcraft_guideme-neoforge-1.21.1", version.ref = "anvilcraft_guideme"}
guideme = { group = "org.appliedenergistics", name = "guideme", version.ref = "guideme" }
jeiCommonApi = { group = "mezz.jei", name = "jei-1.21.1-common-api", version.ref = "jei" }
jeiForgeApi = { group = "mezz.jei", name = "jei-1.21.1-neoforge-api", version.ref = "jei" }
jeiForgeImpl = { group = "mezz.jei", name = "jei-1.21.1-neoforge", version.ref = "jei" }
jade = { group = "maven.modrinth", name = "jade", version.ref = "jade" }

[plugins]
modDevGradle = { id = "net.neoforged.moddev", version.ref = "modDevGradle" }
lombok = { id = "io.freefair.lombok", version.ref = "lombok" }
