@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package dev.anvilcraft.reverberation.anvil;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;